name: Flutter_Android

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Java to compile Android project
        uses: actions/setup-java@v3.13.0
        with:
          java-version: "1.8"

      - name: Install and set Flutter version
        uses: flutter-actions/setup-flutter@v2.3
        with:
          version: "3.13.9"

      - name: Create the Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
        run:
          # import keystore from secrets
          ls -all
          echo $KEYSTORE_BASE64 | base64 -di > android/key.jks
          echo $KEY_PROPERTIES | base64 -di > android/key.properties

      - name: Restore packages
        run: flutter pub get

      - name: Build Android apk
        run: flutter build apk
      - name: Build Android App Bundle
        run: flutter build apk --split-per-abi

      - name: Publish Android Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: app-release
          path: build/app/outputs/apk/release/app-release.apk
