name: Flutter_Android

on:
  push:
    branches: [master]

jobs:
  build_android:
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Install Flutter
      uses: britannio/action-install-flutter@v1.1
    - name: flutter-android-sdk
      # You may pin to the exact commit or the version.
      # uses: andreujuanc/flutter-android-sdk@e347c4122d3ccf725c153b5e2d6d3b88ec2c3557
      uses: andreujuanc/flutter-android-sdk@v1.0.6
          
          
          
