name: Flutter_Android

on:
  push:
    branches: [master]

jobs:
  build_android:
    runs-on: macos-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Install Flutter
      uses: britannio/action-install-flutter@v1.1
    - name: flutter-android-sdk
      # You may pin to the exact commit or the version.
      # uses: andreujuanc/flutter-android-sdk@e347c4122d3ccf725c153b5e2d6d3b88ec2c3557
      uses: andreujuanc/flutter-android-sdk@v1.0.6
    - name: Builds - build Flutter split APK and create github release
    # You may pin to the exact commit or the version.
    # uses: Dank-del/flutter-build-and-publish-action@32b96a7cef73377fbb92daa41932455b0fadaeef
      uses: Dank-del/flutter-build-and-publish-action@v1
      with:
        # The build target to use
        matrix-target: apk --split-per-abi
    - name: Builds - build Flutter APK and create github release
    # You may pin to the exact commit or the version.
    # uses: Dank-del/flutter-build-and-publish-action@32b96a7cef73377fbb92daa41932455b0fadaeef
      uses: Dank-del/flutter-build-and-publish-action@v1
      with:
        # The build target to use
        matrix-target: apk
    # - name: Flutter MSIX
    #   # You may pin to the exact commit or the version.
    #   # uses: Levi-Lesches/Flutter-MSIX@3ab47bab459827143d792d764711adfd1ee1952f
    #   uses: Levi-Lesches/Flutter-MSIX@v0.1
    #   with:
    #     # Whether this action should use a cached version of Flutter. Defaults to true
    #     should-cache-flutter: # optional, default is true
    #     # The cache key to use for Flutter. Defaults to flutter-windows, which doesn't update all that often
    #     flutter-cache-key: # optional, default is flutter-windows
    #     # Your base64-encoded certificate. For security, pass this as a repository secret.
    #     base64-certificate: 
    #     # The path to your Windows certificate (.pfx) file, as it appears in your pubspec.yaml
    #     certificate-path: 
    #     # The path where the MSIX file will be generated. This is a combination of the output_path and output_name properties in package:msix
    #     msix-path: 
    #     # The name of the generated release. Defaults to the tag name, if any. This is passed directly to softprops/action-gh-release
    #     release-name: # optional
    #     # Text to use as the body of the release. This is passed directly to softprops/action-gh-release
    #     release-body: # optional
    #     # A file to use as the body of the release. This is passed directly to softprops/action-gh-release
    #     release-body-path: # optional
    #     # Whether this release should be a draft. This is passed directly to softprops/action-gh-release
    #     release-is-draft: # optional
    #     # Whether to automatically generate release notes. This is passed directly to softprops/action-gh-release
    #     generate-release-notes: # optional, default is true
          
          
          
          
          
