name: app-build-action
#推送Tag时触发
on:
  push:
    branches:
      - master 
jobs:
  build-mac-ios-android:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      #签出代码 
      - uses: actions/checkout@v3
        with:
          ref: master
      #读取版本信息
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/version.json
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"
      #上传至Release
      - name: Upload Release
        uses: julien-deramond/update-issue-body@v1.1.0
        with:
          token: ${{ secrets.TOKEN }}
          body: ${{ fromJson(steps.version.outputs.content).version_desc }}
          issue-number: 62
          
      #完成
      - run: echo "🍏 This job's status is ${{ job.status }}."
